// <auto-generated />
namespace EnrollmentApplication.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _102619 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_102619));
        
        string IMigrationMetadata.Id
        {
            get { return "201910261726594_102619"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
