using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Data.Entity;

namespace FinalEventApplication.Models
{
	public class SampleData : DropCreateDatabaseIfModelChanges<FinalEventApplicationDB>
    {
        protected override void Seed(FinalEventApplicationDB context)
        {
            var Venues = new List<Venue>
            {
                new Venue { Name = "Rock" },
                new Venue { Name = "Jazz" },
                new Venue { Name = "Metal" },
                new Venue { Name = "Alternative" },
                new Venue { Name = "Disco" },
                new Venue { Name = "Blues" },
                new Venue { Name = "Latin" },
                new Venue { Name = "Reggae" },
                new Venue { Name = "Pop" },
                new Venue { Name = "Classical" }
            };

            var Organizers = new List<Organizer>
            {
                new Organizer { Name = "Aaron Copland & London Symphony Orchestra" },
                new Organizer { Name = "Aaron Goldberg" },
                new Organizer { Name = "AC/DC" },
                new Organizer { Name = "Accept" },
                new Organizer { Name = "Adrian Leaper & Doreen de Feis" },
                new Organizer { Name = "Aerosmith" },
                new Organizer { Name = "Aisha Duo" },
                new Organizer { Name = "Alanis Morissette" },
                new Organizer { Name = "Alberto Turco & Nova Schola Gregoriana" },
                new Organizer { Name = "Alice In Chains" },
                new Organizer { Name = "Amy Winehouse" },
                new Organizer { Name = "Anita Ward" },
                new Organizer { Name = "Antônio Carlos Jobim" },
                new Organizer { Name = "Apocalyptica" },
                new Organizer { Name = "Audioslave" },
                new Organizer { Name = "Barry Wordsworth & BBC Concert Orchestra" },
                new Organizer { Name = "Berliner Philharmoniker & Hans Rosbaud" },
                new Organizer { Name = "Berliner Philharmoniker & Herbert Von Karajan" },
                new Organizer { Name = "Billy Cobham" },
                new Organizer { Name = "Black Label Society" },
                new Organizer { Name = "Black Sabbath" },
                new Organizer { Name = "Boston Symphony Orchestra & Seiji Ozawa" },
                new Organizer { Name = "Britten Sinfonia, Ivor Bolton & Lesley Garrett" },
                new Organizer { Name = "Bruce Dickinson" },
                new Organizer { Name = "Buddy Guy" },
                new Organizer { Name = "Caetano Veloso" },
                new Organizer { Name = "Cake" },
                new Organizer { Name = "Calexico" },
                new Organizer { Name = "Cássia Eller" },
                new Organizer { Name = "Chic" },
                new Organizer { Name = "Chicago Symphony Orchestra & Fritz Reiner" },
                new Organizer { Name = "Chico Buarque" },
                new Organizer { Name = "Chico Science & Nação Zumbi" },
                new Organizer { Name = "Choir Of Westminster Abbey & Simon Preston" },
                new Organizer { Name = "Chris Cornell" },
                new Organizer { Name = "Christopher O'Riley" },
                new Organizer { Name = "Cidade Negra" },
                new Organizer { Name = "Cláudio Zoli" },
                new Organizer { Name = "Creedence Clearwater Revival" },
                new Organizer { Name = "David Coverdale" },
                new Organizer { Name = "Deep Purple" },
                new Organizer { Name = "Dennis Chambers" },
                new Organizer { Name = "Djavan" },
                new Organizer { Name = "Donna Summer" },
                new Organizer { Name = "Dread Zeppelin" },
                new Organizer { Name = "Ed Motta" },
                new Organizer { Name = "Edo de Waart & San Francisco Symphony" },
                new Organizer { Name = "Elis Regina" },
                new Organizer { Name = "English Concert & Trevor Pinnock" },
                new Organizer { Name = "Eric Clapton" },
                new Organizer { Name = "Eugene Ormandy" },
                new Organizer { Name = "Faith No More" },
                new Organizer { Name = "Falamansa" },
                new Organizer { Name = "Foo Fighters" },
                new Organizer { Name = "Frank Zappa & Captain Beefheart" },
                new Organizer { Name = "Fretwork" },
                new Organizer { Name = "Funk Como Le Gusta" },
                new Organizer { Name = "Gerald Moore" },
                new Organizer { Name = "Gilberto Gil" },
                new Organizer { Name = "Godsmack" },
                new Organizer { Name = "Gonzaguinha" },
                new Organizer { Name = "Göteborgs Symfoniker & Neeme Järvi" },
                new Organizer { Name = "Guns N' Roses" },
                new Organizer { Name = "Gustav Mahler" },
                new Organizer { Name = "Incognito" },
                new Organizer { Name = "Iron Maiden" },
                new Organizer { Name = "James Levine" },
                new Organizer { Name = "Jamiroquai" },
                new Organizer { Name = "Jimi Hendrix" },
                new Organizer { Name = "Joe Satriani" },
                new Organizer { Name = "Jorge Ben" },
                new Organizer { Name = "Jota Quest" },
                new Organizer { Name = "Judas Priest" },
                new Organizer { Name = "Julian Bream" },
                new Organizer { Name = "Kent Nagano and Orchestre de l'Opéra de Lyon" },
                new Organizer { Name = "Kiss" },
                new Organizer { Name = "Led Zeppelin" },
                new Organizer { Name = "Legião Urbana" },
                new Organizer { Name = "Lenny Kravitz" },
                new Organizer { Name = "Les Arts Florissants & William Christie" },
                new Organizer { Name = "London Symphony Orchestra & Sir Charles Mackerras" },
                new Organizer { Name = "Luciana Souza/Romero Lubambo" },
                new Organizer { Name = "Lulu Santos" },
                new Organizer { Name = "Marcos Valle" },
                new Organizer { Name = "Marillion" },
                new Organizer { Name = "Marisa Monte" },
                new Organizer { Name = "Martin Roscoe" },
                new Organizer { Name = "Maurizio Pollini" },
                new Organizer { Name = "Mela Tenenbaum, Pro Musica Prague & Richard Kapp" },
                new Organizer { Name = "Men At Work" },
                new Organizer { Name = "Metallica" },
                new Organizer { Name = "Michael Tilson Thomas & San Francisco Symphony" },
                new Organizer { Name = "Miles Davis" },
                new Organizer { Name = "Milton Nascimento" },
                new Organizer { Name = "Mötley Crüe" },
                new Organizer { Name = "Motörhead" },
                new Organizer { Name = "Nash Ensemble" },
                new Organizer { Name = "Nicolaus Esterhazy Sinfonia" },
                new Organizer { Name = "Nirvana" },
                new Organizer { Name = "O Terço" },
                new Organizer { Name = "Olodum" },
                new Organizer { Name = "Orchestra of The Age of Enlightenment" },
                new Organizer { Name = "Os Paralamas Do Sucesso" },
                new Organizer { Name = "Ozzy Osbourne" },
                new Organizer { Name = "Page & Plant" },
                new Organizer { Name = "Paul D'Ianno" },
                new Organizer { Name = "Pearl Jam" },
                new Organizer { Name = "Pink Floyd" },
                new Organizer { Name = "Queen" },
                new Organizer { Name = "R.E.M." },
                new Organizer { Name = "Raul Seixas" },
                new Organizer { Name = "Red Hot Chili Peppers" },
                new Organizer { Name = "Roger Norrington, London Classical Players" },
                new Organizer { Name = "Royal Philharmonic Orchestra & Sir Thomas Beecham" },
                new Organizer { Name = "Rush" },
                new Organizer { Name = "Santana" },
                new Organizer { Name = "Scholars Baroque Ensemble" },
                new Organizer { Name = "Scorpions" },
                new Organizer { Name = "Sergei Prokofiev & Yuri Temirkanov" },
                new Organizer { Name = "Sir Georg Solti & Wiener Philharmoniker" },
                new Organizer { Name = "Skank" },
                new Organizer { Name = "Soundgarden" },
                new Organizer { Name = "Spyro Gyra" },
                new Organizer { Name = "Stevie Ray Vaughan & Double Trouble" },
                new Organizer { Name = "Stone Temple Pilots" },
                new Organizer { Name = "System Of A Down" },
                new Organizer { Name = "Temple of the Dog" },
                new Organizer { Name = "Terry Bozzio, Tony Levin & Steve Stevens" },
                new Organizer { Name = "The 12 Cellists of The Berlin Philharmonic" },
                new Organizer { Name = "The Black Crowes" },
                new Organizer { Name = "The Cult" },
                new Organizer { Name = "The Doors" },
                new Organizer { Name = "The King's Singers" },
                new Organizer { Name = "The Police" },
                new Organizer { Name = "The Posies" },
                new Organizer { Name = "The Rolling Stones" },
                new Organizer { Name = "The Who" },
                new Organizer { Name = "Tim Maia" },
                new Organizer { Name = "Ton Koopman" },
                new Organizer { Name = "U2" },
                new Organizer { Name = "UB40" },
                new Organizer { Name = "Van Halen" },
                new Organizer { Name = "Various Organizers" },
                new Organizer { Name = "Velvet Revolver" },
                new Organizer { Name = "Vinícius De Moraes" },
                new Organizer { Name = "Wilhelm Kempff" },
                new Organizer { Name = "Yehudi Menuhin" },
                new Organizer { Name = "Yo-Yo Ma" },
                new Organizer { Name = "Zeca Pagodinho" }
            };

            new List<Event>
            {
                new Event { Title = "A Copland Celebration, Vol. I", Venue = Venues.Single(g => g.Name == "Classical"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "Aaron Copland & London Symphony Orchestra"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "Worlds", Venue = Venues.Single(g => g.Name == "Jazz"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "Aaron Goldberg"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "For Those About To Rock We Salute You", Venue = Venues.Single(g => g.Name == "Rock"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "AC/DC"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "Let There Be Rock", Venue = Venues.Single(g => g.Name == "Rock"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "AC/DC"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "Balls to the Wall", Venue = Venues.Single(g => g.Name == "Rock"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "Accept"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "Restless and Wild", Venue = Venues.Single(g => g.Name == "Rock"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "Accept"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "Górecki: Symphony No. 3", Venue = Venues.Single(g => g.Name == "Classical"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "Adrian Leaper & Doreen de Feis"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "Big Ones", Venue = Venues.Single(g => g.Name == "Rock"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "Aerosmith"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "Quiet Songs", Venue = Venues.Single(g => g.Name == "Jazz"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "Aisha Duo"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "Jagged Little Pill", Venue = Venues.Single(g => g.Name == "Rock"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "Alanis Morissette"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "Facelift", Venue = Venues.Single(g => g.Name == "Rock"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "Alice In Chains"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "Frank", Venue = Venues.Single(g => g.Name == "Pop"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "Amy Winehouse"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "Ring My Bell", Venue = Venues.Single(g => g.Name == "Disco"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "Anita Ward"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "Chill: Brazil (Disc 2)", Venue = Venues.Single(g => g.Name == "Latin"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "Antônio Carlos Jobim"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "Warner 25 Anos", Venue = Venues.Single(g => g.Name == "Jazz"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "Antônio Carlos Jobim"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "Plays Metallica By Four Cellos", Venue = Venues.Single(g => g.Name == "Metal"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "Apocalyptica"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "Revelations", Venue = Venues.Single(g => g.Name == "Alternative"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "Audioslave"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "Audioslave", Venue = Venues.Single(g => g.Name == "Rock"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "Audioslave"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "The Last Night of the Proms", Venue = Venues.Single(g => g.Name == "Classical"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "Barry Wordsworth & BBC Concert Orchestra"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "Sibelius: Finlandia", Venue = Venues.Single(g => g.Name == "Classical"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "Berliner Philharmoniker & Hans Rosbaud"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "Mozart: Symphonies Nos. 40 & 41", Venue = Venues.Single(g => g.Name == "Classical"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "Berliner Philharmoniker & Herbert Von Karajan"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "The Best Of Billy Cobham", Venue = Venues.Single(g => g.Name == "Jazz"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "Billy Cobham"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "Alcohol Fueled Brewtality Live! [Disc 1]", Venue = Venues.Single(g => g.Name == "Metal"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "Black Label Society"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "Alcohol Fueled Brewtality Live! [Disc 2]", Venue = Venues.Single(g => g.Name == "Metal"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "Black Label Society"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "Black Sabbath Vol. 4 (Remaster)", Venue = Venues.Single(g => g.Name == "Metal"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "Black Sabbath"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "Black Sabbath", Venue = Venues.Single(g => g.Name == "Metal"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "Black Sabbath"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "Carmina Burana", Venue = Venues.Single(g => g.Name == "Classical"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "Boston Symphony Orchestra & Seiji Ozawa"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "A Soprano Inspired", Venue = Venues.Single(g => g.Name == "Classical"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "Britten Sinfonia, Ivor Bolton & Lesley Garrett"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "Chemical Wedding", Venue = Venues.Single(g => g.Name == "Metal"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "Bruce Dickinson"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "Prenda Minha", Venue = Venues.Single(g => g.Name == "Latin"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "Caetano Veloso"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "Sozinho Remix Ao Vivo", Venue = Venues.Single(g => g.Name == "Latin"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "Caetano Veloso"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "Cake: B-Sides and Rarities", Venue = Venues.Single(g => g.Name == "Alternative"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "Cake"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "Carried to Dust (Bonus Track Version)", Venue = Venues.Single(g => g.Name == "Alternative"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "Calexico"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "Cássia Eller - Sem Limite [Disc 1]", Venue = Venues.Single(g => g.Name == "Latin"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "Cássia Eller"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "Le Freak", Venue = Venues.Single(g => g.Name == "Disco"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "Chic"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "Scheherazade", Venue = Venues.Single(g => g.Name == "Classical"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "Chicago Symphony Orchestra & Fritz Reiner"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "Minha Historia", Venue = Venues.Single(g => g.Name == "Latin"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "Chico Buarque"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "Afrociberdelia", Venue = Venues.Single(g => g.Name == "Latin"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "Chico Science & Nação Zumbi"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "Da Lama Ao Caos", Venue = Venues.Single(g => g.Name == "Latin"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "Chico Science & Nação Zumbi"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "Carry On", Venue = Venues.Single(g => g.Name == "Alternative"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "Chris Cornell"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "SCRIABIN: Vers la flamme", Venue = Venues.Single(g => g.Name == "Classical"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "Christopher O'Riley"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "Acústico MTV [Live]", Venue = Venues.Single(g => g.Name == "Reggae"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "Cidade Negra"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "Cidade Negra - Hits", Venue = Venues.Single(g => g.Name == "Reggae"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "Cidade Negra"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "Na Pista", Venue = Venues.Single(g => g.Name == "Latin"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "Cláudio Zoli"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "Chronicle, Vol. 1", Venue = Venues.Single(g => g.Name == "Rock"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "Creedence Clearwater Revival"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "Chronicle, Vol. 2", Venue = Venues.Single(g => g.Name == "Rock"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "Creedence Clearwater Revival"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "Into The Light", Venue = Venues.Single(g => g.Name == "Rock"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "David Coverdale"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "Come Taste The Band", Venue = Venues.Single(g => g.Name == "Rock"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "Deep Purple"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "Deep Purple In Rock", Venue = Venues.Single(g => g.Name == "Rock"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "Deep Purple"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "Fireball", Venue = Venues.Single(g => g.Name == "Rock"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "Deep Purple"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "Machine Head", Venue = Venues.Single(g => g.Name == "Rock"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "Deep Purple"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "MK III The Final Concerts [Disc 1]", Venue = Venues.Single(g => g.Name == "Rock"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "Deep Purple"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "Purpendicular", Venue = Venues.Single(g => g.Name == "Rock"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "Deep Purple"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "Slaves And Masters", Venue = Venues.Single(g => g.Name == "Rock"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "Deep Purple"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "Stormbringer", Venue = Venues.Single(g => g.Name == "Rock"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "Deep Purple"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "The Battle Rages On", Venue = Venues.Single(g => g.Name == "Rock"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "Deep Purple"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "The Final Concerts (Disc 2)", Venue = Venues.Single(g => g.Name == "Rock"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "Deep Purple"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "Outbreak", Venue = Venues.Single(g => g.Name == "Jazz"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "Dennis Chambers"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "Djavan Ao Vivo - Vol. 02", Venue = Venues.Single(g => g.Name == "Latin"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "Djavan"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "Djavan Ao Vivo - Vol. 1", Venue = Venues.Single(g => g.Name == "Latin"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "Djavan"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "MacArthur Park Suite", Venue = Venues.Single(g => g.Name == "Disco"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "Donna Summer"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "Un-Led-Ed", Venue = Venues.Single(g => g.Name == "Rock"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "Dread Zeppelin"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "The Best of Ed Motta", Venue = Venues.Single(g => g.Name == "Latin"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "Ed Motta"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "Adams, John: The Chairman Dances", Venue = Venues.Single(g => g.Name == "Classical"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "Edo de Waart & San Francisco Symphony"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "Elis Regina-Minha História", Venue = Venues.Single(g => g.Name == "Latin"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "Elis Regina"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "Pachelbel: Canon & Gigue", Venue = Venues.Single(g => g.Name == "Classical"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "English Concert & Trevor Pinnock"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "Unplugged", Venue = Venues.Single(g => g.Name == "Latin"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "Eric Clapton"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "The Cream Of Clapton", Venue = Venues.Single(g => g.Name == "Blues"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "Eric Clapton"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "Unplugged", Venue = Venues.Single(g => g.Name == "Blues"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "Eric Clapton"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "Respighi:Pines of Rome", Venue = Venues.Single(g => g.Name == "Classical"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "Eugene Ormandy"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "Strauss: Waltzes", Venue = Venues.Single(g => g.Name == "Classical"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "Eugene Ormandy"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "King For A Day Fool For A Lifetime", Venue = Venues.Single(g => g.Name == "Rock"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "Faith No More"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "Deixa Entrar", Venue = Venues.Single(g => g.Name == "Latin"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "Falamansa"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "In Your Honor [Disc 1]", Venue = Venues.Single(g => g.Name == "Rock"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "Foo Fighters"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "In Your Honor [Disc 2]", Venue = Venues.Single(g => g.Name == "Rock"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "Foo Fighters"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "The Colour And The Shape", Venue = Venues.Single(g => g.Name == "Rock"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "Foo Fighters"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "Bongo Fury", Venue = Venues.Single(g => g.Name == "Rock"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "Frank Zappa & Captain Beefheart"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "Roda De Funk", Venue = Venues.Single(g => g.Name == "Latin"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "Funk Como Le Gusta"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "Quanta Gente Veio Ver (Live)", Venue = Venues.Single(g => g.Name == "Latin"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "Gilberto Gil"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "Quanta Gente Veio ver--Bônus De Carnaval", Venue = Venues.Single(g => g.Name == "Jazz"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "Gilberto Gil"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "Faceless", Venue = Venues.Single(g => g.Name == "Metal"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "Godsmack"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "Meus Momentos", Venue = Venues.Single(g => g.Name == "Latin"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "Gonzaguinha"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "Nielsen: The Six Symphonies", Venue = Venues.Single(g => g.Name == "Classical"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "Göteborgs Symfoniker & Neeme Järvi"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "Appetite for Destruction", Venue = Venues.Single(g => g.Name == "Rock"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "Guns N' Roses"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "Use Your Illusion I", Venue = Venues.Single(g => g.Name == "Rock"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "Guns N' Roses"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "Use Your Illusion II", Venue = Venues.Single(g => g.Name == "Metal"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "Guns N' Roses"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "Blue Moods", Venue = Venues.Single(g => g.Name == "Jazz"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "Incognito"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "A Matter of Life and Death", Venue = Venues.Single(g => g.Name == "Rock"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "Iron Maiden"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "Brave New World", Venue = Venues.Single(g => g.Name == "Rock"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "Iron Maiden"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "Fear Of The Dark", Venue = Venues.Single(g => g.Name == "Rock"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "Iron Maiden"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "Live At Donington 1992 (Disc 1)", Venue = Venues.Single(g => g.Name == "Rock"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "Iron Maiden"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "Live At Donington 1992 (Disc 2)", Venue = Venues.Single(g => g.Name == "Rock"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "Iron Maiden"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "Rock In Rio [CD2]", Venue = Venues.Single(g => g.Name == "Rock"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "Iron Maiden"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "The Number of The Beast", Venue = Venues.Single(g => g.Name == "Rock"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "Iron Maiden"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "The X Factor", Venue = Venues.Single(g => g.Name == "Rock"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "Iron Maiden"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "Virtual XI", Venue = Venues.Single(g => g.Name == "Rock"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "Iron Maiden"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "A Real Dead One", Venue = Venues.Single(g => g.Name == "Metal"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "Iron Maiden"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "A Real Live One", Venue = Venues.Single(g => g.Name == "Metal"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "Iron Maiden"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "Live After Death", Venue = Venues.Single(g => g.Name == "Metal"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "Iron Maiden"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "No Prayer For The Dying", Venue = Venues.Single(g => g.Name == "Metal"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "Iron Maiden"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "Piece Of Mind", Venue = Venues.Single(g => g.Name == "Metal"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "Iron Maiden"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "Powerslave", Venue = Venues.Single(g => g.Name == "Metal"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "Iron Maiden"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "Rock In Rio [CD1]", Venue = Venues.Single(g => g.Name == "Metal"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "Iron Maiden"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "Rock In Rio [CD2]", Venue = Venues.Single(g => g.Name == "Metal"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "Iron Maiden"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "Seventh Son of a Seventh Son", Venue = Venues.Single(g => g.Name == "Metal"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "Iron Maiden"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "Somewhere in Time", Venue = Venues.Single(g => g.Name == "Metal"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "Iron Maiden"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "The Number of The Beast", Venue = Venues.Single(g => g.Name == "Metal"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "Iron Maiden"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "Iron Maiden", Venue = Venues.Single(g => g.Name == "Blues"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "Iron Maiden"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "Mascagni: Cavalleria Rusticana", Venue = Venues.Single(g => g.Name == "Classical"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "James Levine"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "Emergency On Planet Earth", Venue = Venues.Single(g => g.Name == "Rock"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "Jamiroquai"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "Are You Experienced?", Venue = Venues.Single(g => g.Name == "Rock"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "Jimi Hendrix"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "Surfing with the Alien (Remastered)", Venue = Venues.Single(g => g.Name == "Rock"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "Joe Satriani"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "Jorge Ben Jor 25 Anos", Venue = Venues.Single(g => g.Name == "Latin"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "Jorge Ben"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "Jota Quest-1995", Venue = Venues.Single(g => g.Name == "Latin"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "Jota Quest"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "Living After Midnight", Venue = Venues.Single(g => g.Name == "Metal"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "Judas Priest"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "Weill: The Seven Deadly Sins", Venue = Venues.Single(g => g.Name == "Classical"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "Kent Nagano and Orchestre de l'Opéra de Lyon"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "Greatest Kiss", Venue = Venues.Single(g => g.Name == "Rock"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "Kiss"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "Unplugged [Live]", Venue = Venues.Single(g => g.Name == "Rock"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "Kiss"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "BBC Sessions [Disc 1] [Live]", Venue = Venues.Single(g => g.Name == "Rock"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "Led Zeppelin"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "BBC Sessions [Disc 2] [Live]", Venue = Venues.Single(g => g.Name == "Rock"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "Led Zeppelin"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "Coda", Venue = Venues.Single(g => g.Name == "Rock"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "Led Zeppelin"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "Houses Of The Holy", Venue = Venues.Single(g => g.Name == "Rock"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "Led Zeppelin"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "In Through The Out Door", Venue = Venues.Single(g => g.Name == "Rock"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "Led Zeppelin"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "IV", Venue = Venues.Single(g => g.Name == "Rock"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "Led Zeppelin"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "Led Zeppelin I", Venue = Venues.Single(g => g.Name == "Rock"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "Led Zeppelin"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "Led Zeppelin II", Venue = Venues.Single(g => g.Name == "Rock"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "Led Zeppelin"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "Led Zeppelin III", Venue = Venues.Single(g => g.Name == "Rock"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "Led Zeppelin"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "Physical Graffiti [Disc 1]", Venue = Venues.Single(g => g.Name == "Rock"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "Led Zeppelin"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "Physical Graffiti [Disc 2]", Venue = Venues.Single(g => g.Name == "Rock"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "Led Zeppelin"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "Presence", Venue = Venues.Single(g => g.Name == "Rock"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "Led Zeppelin"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "The Song Remains The Same (Disc 1)", Venue = Venues.Single(g => g.Name == "Rock"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "Led Zeppelin"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "The Song Remains The Same (Disc 2)", Venue = Venues.Single(g => g.Name == "Rock"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "Led Zeppelin"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "Mais Do Mesmo", Venue = Venues.Single(g => g.Name == "Latin"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "Legião Urbana"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "Greatest Hits", Venue = Venues.Single(g => g.Name == "Reggae"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "Lenny Kravitz"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "Greatest Hits", Venue = Venues.Single(g => g.Name == "Rock"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "Lenny Kravitz"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "Greatest Hits", Venue = Venues.Single(g => g.Name == "Metal"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "Lenny Kravitz"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "Tchaikovsky: The Nutcracker", Venue = Venues.Single(g => g.Name == "Classical"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "London Symphony Orchestra & Sir Charles Mackerras"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "Duos II", Venue = Venues.Single(g => g.Name == "Latin"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "Luciana Souza/Romero Lubambo"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "Chill: Brazil (Disc 1)", Venue = Venues.Single(g => g.Name == "Latin"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "Marcos Valle"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "Misplaced Childhood", Venue = Venues.Single(g => g.Name == "Rock"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "Marillion"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "Barulhinho Bom", Venue = Venues.Single(g => g.Name == "Latin"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "Marisa Monte"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "Szymanowski: Piano Works, Vol. 1", Venue = Venues.Single(g => g.Name == "Classical"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "Martin Roscoe"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "The Best Of Men At Work", Venue = Venues.Single(g => g.Name == "Rock"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "Men At Work"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "...And Justice For All", Venue = Venues.Single(g => g.Name == "Metal"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "Metallica"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "Black Event", Venue = Venues.Single(g => g.Name == "Metal"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "Metallica"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "Garage Inc. (Disc 1)", Venue = Venues.Single(g => g.Name == "Metal"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "Metallica"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "Garage Inc. (Disc 2)", Venue = Venues.Single(g => g.Name == "Metal"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "Metallica"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "Load", Venue = Venues.Single(g => g.Name == "Metal"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "Metallica"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "Master Of Puppets", Venue = Venues.Single(g => g.Name == "Metal"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "Metallica"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "ReLoad", Venue = Venues.Single(g => g.Name == "Metal"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "Metallica"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "Ride The Lightning", Venue = Venues.Single(g => g.Name == "Metal"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "Metallica"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "St. Anger", Venue = Venues.Single(g => g.Name == "Metal"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "Metallica"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "Berlioz: Symphonie Fantastique", Venue = Venues.Single(g => g.Name == "Classical"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "Michael Tilson Thomas & San Francisco Symphony"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "Prokofiev: Romeo & Juliet", Venue = Venues.Single(g => g.Name == "Classical"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "Michael Tilson Thomas & San Francisco Symphony"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "Miles Ahead", Venue = Venues.Single(g => g.Name == "Jazz"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "Miles Davis"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "The Essential Miles Davis [Disc 1]", Venue = Venues.Single(g => g.Name == "Jazz"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "Miles Davis"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "The Essential Miles Davis [Disc 2]", Venue = Venues.Single(g => g.Name == "Jazz"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "Miles Davis"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "Milton Nascimento Ao Vivo", Venue = Venues.Single(g => g.Name == "Latin"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "Milton Nascimento"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "Minas", Venue = Venues.Single(g => g.Name == "Latin"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "Milton Nascimento"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "Motley Crue Greatest Hits", Venue = Venues.Single(g => g.Name == "Metal"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "Mötley Crüe"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "Ace Of Spades", Venue = Venues.Single(g => g.Name == "Metal"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "Motörhead"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "Mozart: Chamber Music", Venue = Venues.Single(g => g.Name == "Classical"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "Nash Ensemble"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "The Best of Beethoven", Venue = Venues.Single(g => g.Name == "Classical"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "Nicolaus Esterhazy Sinfonia"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "Nevermind", Venue = Venues.Single(g => g.Name == "Rock"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "Nirvana"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "Compositores", Venue = Venues.Single(g => g.Name == "Rock"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "O Terço"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "Olodum", Venue = Venues.Single(g => g.Name == "Latin"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "Olodum"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "Bach: The Brandenburg Concertos", Venue = Venues.Single(g => g.Name == "Classical"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "Orchestra of The Age of Enlightenment"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "Acústico MTV", Venue = Venues.Single(g => g.Name == "Latin"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "Os Paralamas Do Sucesso"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "Arquivo II", Venue = Venues.Single(g => g.Name == "Latin"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "Os Paralamas Do Sucesso"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "Arquivo Os Paralamas Do Sucesso", Venue = Venues.Single(g => g.Name == "Latin"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "Os Paralamas Do Sucesso"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "Tribute", Venue = Venues.Single(g => g.Name == "Metal"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "Ozzy Osbourne"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "Bark at the Moon (Remastered)", Venue = Venues.Single(g => g.Name == "Rock"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "Ozzy Osbourne"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "Blizzard of Ozz", Venue = Venues.Single(g => g.Name == "Rock"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "Ozzy Osbourne"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "Diary of a Madman (Remastered)", Venue = Venues.Single(g => g.Name == "Rock"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "Ozzy Osbourne"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "No More Tears (Remastered)", Venue = Venues.Single(g => g.Name == "Rock"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "Ozzy Osbourne"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "Speak of the Devil", Venue = Venues.Single(g => g.Name == "Rock"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "Ozzy Osbourne"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "Walking Into Clarksdale", Venue = Venues.Single(g => g.Name == "Rock"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "Page & Plant"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "The Beast Live", Venue = Venues.Single(g => g.Name == "Rock"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "Paul D'Ianno"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "Live On Two Legs [Live]", Venue = Venues.Single(g => g.Name == "Rock"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "Pearl Jam"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "Riot Act", Venue = Venues.Single(g => g.Name == "Rock"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "Pearl Jam"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "Ten", Venue = Venues.Single(g => g.Name == "Rock"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "Pearl Jam"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "Vs.", Venue = Venues.Single(g => g.Name == "Rock"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "Pearl Jam"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "Dark Side Of The Moon", Venue = Venues.Single(g => g.Name == "Rock"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "Pink Floyd"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "Greatest Hits I", Venue = Venues.Single(g => g.Name == "Rock"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "Queen"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "Greatest Hits II", Venue = Venues.Single(g => g.Name == "Rock"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "Queen"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "News Of The World", Venue = Venues.Single(g => g.Name == "Rock"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "Queen"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "New Adventures In Hi-Fi", Venue = Venues.Single(g => g.Name == "Rock"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "R.E.M."), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "Raul Seixas", Venue = Venues.Single(g => g.Name == "Rock"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "Raul Seixas"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "By The Way", Venue = Venues.Single(g => g.Name == "Rock"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "Red Hot Chili Peppers"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "Californication", Venue = Venues.Single(g => g.Name == "Rock"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "Red Hot Chili Peppers"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "Purcell: The Fairy Queen", Venue = Venues.Single(g => g.Name == "Classical"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "Roger Norrington, London Classical Players"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "Haydn: Symphonies 99 - 104", Venue = Venues.Single(g => g.Name == "Classical"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "Royal Philharmonic Orchestra & Sir Thomas Beecham"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "Retrospective I (1974-1980)", Venue = Venues.Single(g => g.Name == "Rock"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "Rush"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "Santana - As Years Go By", Venue = Venues.Single(g => g.Name == "Rock"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "Santana"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "Santana Live", Venue = Venues.Single(g => g.Name == "Rock"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "Santana"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "Supernatural", Venue = Venues.Single(g => g.Name == "Rock"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "Santana"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "Handel: The Messiah (Highlights)", Venue = Venues.Single(g => g.Name == "Classical"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "Scholars Baroque Ensemble"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "Prokofiev: Symphony No.1", Venue = Venues.Single(g => g.Name == "Classical"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "Sergei Prokofiev & Yuri Temirkanov"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "Wagner: Favourite Overtures", Venue = Venues.Single(g => g.Name == "Classical"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "Sir Georg Solti & Wiener Philharmoniker"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "Maquinarama", Venue = Venues.Single(g => g.Name == "Rock"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "Skank"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "O Samba Poconé", Venue = Venues.Single(g => g.Name == "Rock"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "Skank"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "A-Sides", Venue = Venues.Single(g => g.Name == "Rock"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "Soundgarden"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "Heart of the Night", Venue = Venues.Single(g => g.Name == "Jazz"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "Spyro Gyra"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "Morning Dance", Venue = Venues.Single(g => g.Name == "Jazz"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "Spyro Gyra"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "In Step", Venue = Venues.Single(g => g.Name == "Blues"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "Stevie Ray Vaughan & Double Trouble"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "Core", Venue = Venues.Single(g => g.Name == "Rock"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "Stone Temple Pilots"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "Mezmerize", Venue = Venues.Single(g => g.Name == "Metal"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "System Of A Down"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "Temple of the Dog", Venue = Venues.Single(g => g.Name == "Alternative"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "Temple of the Dog"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "[1997] Black Light Syndrome", Venue = Venues.Single(g => g.Name == "Rock"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "Terry Bozzio, Tony Levin & Steve Stevens"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "South American Getaway", Venue = Venues.Single(g => g.Name == "Classical"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "The 12 Cellists of The Berlin Philharmonic"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "Live [Disc 1]", Venue = Venues.Single(g => g.Name == "Blues"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "The Black Crowes"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "Live [Disc 2]", Venue = Venues.Single(g => g.Name == "Blues"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "The Black Crowes"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "Beyond Good And Evil", Venue = Venues.Single(g => g.Name == "Rock"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "The Cult"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "The Doors", Venue = Venues.Single(g => g.Name == "Rock"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "The Doors"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "English Renaissance", Venue = Venues.Single(g => g.Name == "Classical"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "The King's Singers"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "The Police Greatest Hits", Venue = Venues.Single(g => g.Name == "Rock"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "The Police"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "Every Kind of Light", Venue = Venues.Single(g => g.Name == "Rock"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "The Posies"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "Hot Rocks, 1964-1971 (Disc 1)", Venue = Venues.Single(g => g.Name == "Rock"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "The Rolling Stones"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "No Security", Venue = Venues.Single(g => g.Name == "Rock"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "The Rolling Stones"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "Voodoo Lounge", Venue = Venues.Single(g => g.Name == "Rock"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "The Rolling Stones"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "My Generation - The Very Best Of The Who", Venue = Venues.Single(g => g.Name == "Rock"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "The Who"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "Serie Sem Limite (Disc 1)", Venue = Venues.Single(g => g.Name == "Latin"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "Tim Maia"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "Serie Sem Limite (Disc 2)", Venue = Venues.Single(g => g.Name == "Latin"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "Tim Maia"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "Bach: Toccata & Fugue in D Minor", Venue = Venues.Single(g => g.Name == "Classical"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "Ton Koopman"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "Achtung Baby", Venue = Venues.Single(g => g.Name == "Rock"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "U2"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "B-Sides 1980-1990", Venue = Venues.Single(g => g.Name == "Rock"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "U2"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "How To Dismantle An Atomic Bomb", Venue = Venues.Single(g => g.Name == "Rock"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "U2"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "Pop", Venue = Venues.Single(g => g.Name == "Rock"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "U2"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "Rattle And Hum", Venue = Venues.Single(g => g.Name == "Rock"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "U2"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "The Best Of 1980-1990", Venue = Venues.Single(g => g.Name == "Rock"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "U2"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "War", Venue = Venues.Single(g => g.Name == "Rock"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "U2"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "Zooropa", Venue = Venues.Single(g => g.Name == "Rock"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "U2"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "UB40 The Best Of - Volume Two [UK]", Venue = Venues.Single(g => g.Name == "Reggae"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "UB40"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "Diver Down", Venue = Venues.Single(g => g.Name == "Rock"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "Van Halen"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "The Best Of Van Halen, Vol. I", Venue = Venues.Single(g => g.Name == "Rock"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "Van Halen"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "Van Halen III", Venue = Venues.Single(g => g.Name == "Rock"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "Van Halen"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "Van Halen", Venue = Venues.Single(g => g.Name == "Rock"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "Van Halen"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "Axé Bahia 2001", Venue = Venues.Single(g => g.Name == "Pop"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "Various Organizers"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "Sambas De Enredo 2001", Venue = Venues.Single(g => g.Name == "Latin"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "Various Organizers"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "Vozes do MPB", Venue = Venues.Single(g => g.Name == "Latin"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "Various Organizers"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "Contraband", Venue = Venues.Single(g => g.Name == "Rock"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "Velvet Revolver"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "Vinicius De Moraes", Venue = Venues.Single(g => g.Name == "Latin"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "Vinícius De Moraes"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "Bach: Goldberg Variations", Venue = Venues.Single(g => g.Name == "Classical"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "Wilhelm Kempff"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "Bartok: Violin & Viola Concertos", Venue = Venues.Single(g => g.Name == "Classical"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "Yehudi Menuhin"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "Bach: The Cello Suites", Venue = Venues.Single(g => g.Name == "Classical"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "Yo-Yo Ma"), EventArtUrl = "/Content/Images/placeholder.gif" },
                new Event { Title = "Ao Vivo [IMPORT]", Venue = Venues.Single(g => g.Name == "Latin"), Price = 8.99M, Organizer = Organizers.Single(a => a.Name == "Zeca Pagodinho"), EventArtUrl = "/Content/Images/placeholder.gif" },
            }.ForEach(a => context.Events.Add(a));
        }
    }
}