using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Data.Entity;

namespace FinalProject2.Models
{
    public class SeedData : DropCreateDatabaseAlways<MVCEventDB>
    {
        protected override void Seed(MVCEventDB context)
        {
            var eventTypes = new List<EventType>
            {
                new EventType { Name = "Convention" },
                new EventType { Name = "Theatre" },
                new EventType { Name = "Movie" },
                new EventType { Name = "Dining" },
                new EventType { Name = "Concert" },
                new EventType { Name = "Festival" },
                new EventType { Name = "Gathering" },
                new EventType { Name = "Shenanigans" },
                new EventType { Name = "Sporting Event" },
                new EventType { Name = "Meeting" },

            };

            new List<EventType>
            {
                new EventType { Name = "Convention" },
                new EventType { Name = "Theatre" },
                new EventType { Name = "Movie" },
                new EventType { Name = "Dining" },
                new EventType { Name = "Concert" },
                new EventType { Name = "Festival" },
                new EventType { Name = "Gathering" },
                new EventType { Name = "Shenanigans" },
                new EventType { Name = "Sporting Event" },
                new EventType { Name = "Meeting" },

            }.ForEach(a => context.EventTypes.Add(a));


            new List<Event>
            {
                new Event { EventID = 1, MaxTickets = 4705, AvailableTickets = 962, Type = eventTypes.Single(g => g.Name == "Convention"), EventName = "About Face", Description = "Active Duty, and Veterans Convention", StartDate = Convert.ToDateTime("12/12/20 09:01"), EndDate = Convert.ToDateTime("12/12/20 21:29"), VenueName = "The Bushes", VenueCity = "Napalm", VenueState = "VN", OrganizerName = "Charlie", OrganizerEmail = "v@nom.com" },
                new Event { EventID = 2, MaxTickets = 6131, AvailableTickets = 862, Type = eventTypes.Single(g => g.Name == "Theatre"), EventName = "AC/DC", Description = "The rivalry of Edison and Tesla", StartDate = Convert.ToDateTime("1/29/20 18:21"), EndDate = Convert.ToDateTime("3/30/20 15:46"), VenueName = "Electric Avenue Auditorium", VenueCity = "Las Vegas", VenueState = "NV", OrganizerName = "Lyt Ning", OrganizerEmail = "Storms@EternalEnergy.com" },
                new Event { EventID = 3, MaxTickets = 890, AvailableTickets = 142, Type = eventTypes.Single(g => g.Name == "Movie"), EventName = "ADHD", Description = "Unrelated clips strung together for those with no attention span", StartDate = Convert.ToDateTime("4/27/20 22:25"), EndDate = Convert.ToDateTime("4/28/20 00:23"), VenueName = "Daytona Speedway", VenueCity = "Daytona", VenueState = "FL", OrganizerName = "Addy", OrganizerEmail = "Rit@lin.com" },
                new Event { EventID = 4, MaxTickets = 8613, AvailableTickets = 7530, Type = eventTypes.Single(g => g.Name == "Convention"), EventName = "Decepti-con", Description = "Autobots Rollout", StartDate = Convert.ToDateTime("11/11/20 14:06"), EndDate = Convert.ToDateTime("11/11/20 20:48"), VenueName = "Cybertron", VenueCity = "Detroit", VenueState = "MI", OrganizerName = "Optimus", OrganizerEmail = "TheBigO@prime.com" },
                new Event { EventID = 5, MaxTickets = 9165, AvailableTickets = 8899, Type = eventTypes.Single(g => g.Name == "Concert"), EventName = "Afterburner", Description = "Trippy stoner music", StartDate = Convert.ToDateTime("12/26/19 19:13"), EndDate = Convert.ToDateTime("12/27/19 06:56"), VenueName = "Max Yasgur's", VenueCity = "Bethel", VenueState = "NY", OrganizerName = "KidTryppie", OrganizerEmail = "DMTBaby@PillCandy.com" },
                new Event { EventID = 6, MaxTickets = 8071, AvailableTickets = 3154, Type = eventTypes.Single(g => g.Name == "Movie"), EventName = "Aaaah!", Description = "Were you startled?", StartDate = Convert.ToDateTime("11/12/20 15:07"), EndDate = Convert.ToDateTime("11/12/20 23:17"), VenueName = "Real Monsters Stadium", VenueCity = "Cleveland", VenueState = "OH", OrganizerName = "Krumm", OrganizerEmail = "Klasky@nikelodeon.com" },
                new Event { EventID = 7, MaxTickets = 3690, AvailableTickets = 2505, Type = eventTypes.Single(g => g.Name == "Movie"), EventName = "Barknado", Description = "The cone of shame no more", StartDate = Convert.ToDateTime("12/14/19 23:37"), EndDate = Convert.ToDateTime("1/15/20 23:56"), VenueName = "First Energy Stadium", VenueCity = "Cleveland", VenueState = "OH", OrganizerName = "WOOF", OrganizerEmail = "chasingmytail@thepound.com" },
                new Event { EventID = 8, MaxTickets = 660, AvailableTickets = 453, Type = eventTypes.Single(g => g.Name == "Festival"), EventName = "Baconfest", Description = "Crispy, Chewy, Candied", StartDate = Convert.ToDateTime("12/13/19 06:58"), EndDate = Convert.ToDateTime("12/15/19 14:20"), VenueName = "The Pig's Pen", VenueCity = "Pittsburgh", VenueState = "PA", OrganizerName = "E.B. White", OrganizerEmail = "Wilbur@slaughtered.com" },
                new Event { EventID = 9, MaxTickets = 9519, AvailableTickets = 15, Type = eventTypes.Single(g => g.Name == "Movie"), EventName = "Brown Sugar", Description = "An interracial love story", StartDate = Convert.ToDateTime("11/03/20 19:45"), EndDate = Convert.ToDateTime("11/04/20 14:34"), VenueName = "Ebony and Ivory", VenueCity = "Villa Blanco", VenueState = "NM", OrganizerName = "Mrs. Buttersworth", OrganizerEmail = "TastySyrup@pancakebatter.com" },
                new Event { EventID = 10, MaxTickets = 383, AvailableTickets = 293, Type = eventTypes.Single(g => g.Name == "Dining"), EventName = "Bourbon Base", Description = "BBQ, with a boozy base", StartDate = Convert.ToDateTime("11/03/20 10:16"), EndDate = Convert.ToDateTime("11/04/20 00:42"), VenueName = "The Distillery", VenueCity = "Clermont", VenueState = "KY", OrganizerName = "Mr. Beam", OrganizerEmail = "MrBeam@DrinkResposibly.com" },
                new Event { EventID = 11, MaxTickets = 6491, AvailableTickets = 5584, Type = eventTypes.Single(g => g.Name == "Movie"), EventName = "Barn Burners", Description = "Not an Amish Paradise", StartDate = Convert.ToDateTime("11/10/19 19:20"), EndDate = Convert.ToDateTime("11/10/19 19:48"), VenueName = "Jebadiah's Field", VenueCity = "Millersburg", VenueState = "PA", OrganizerName = "Abraham", OrganizerEmail = "" },
                new Event { EventID = 12, MaxTickets = 9540, AvailableTickets = 8423, Type = eventTypes.Single(g => g.Name == "Shenanigans"), EventName = "Bonfire Blowout", Description = "Big fire, not birthday candles", StartDate = Convert.ToDateTime("10/29/20 08:08"), EndDate = Convert.ToDateTime("10/29/20 16:04"), VenueName = "Um...my backyard", VenueCity = "Spearfish", VenueState = "SD", OrganizerName = "Pete", OrganizerEmail = "pgriffin@email.com" },
                new Event { EventID = 13, MaxTickets = 2519, AvailableTickets = 67, Type = eventTypes.Single(g => g.Name == "Festival"), EventName = "Boomstick", Description = "Chainsaw hands, possessed vines, and evil twins", StartDate = Convert.ToDateTime("11/24/20 01:54"), EndDate = Convert.ToDateTime("11/24/20 04:32"), VenueName = "Remote Cabin", VenueCity = "Morristown", VenueState = "TN", OrganizerName = "Bruce", OrganizerEmail = "BoomstickCampbell@evildead.com" },
                new Event { EventID = 14, MaxTickets = 1972, AvailableTickets = 1221, Type = eventTypes.Single(g => g.Name == "Dining"), EventName = "Critters Cafe", Description = "Crickets, Roadkill, and other undesirable dishes", StartDate = Convert.ToDateTime("12/04/20 23:25"), EndDate = Convert.ToDateTime("12/05/20 16:49"), VenueName = "Roadkill Cafe", VenueCity = "Boulder", VenueState = "CO", OrganizerName = "Jimmie Tate", OrganizerEmail = "friedtaters@venis-son.com" },
                new Event { EventID = 15, MaxTickets = 4691, AvailableTickets = 1251, Type = eventTypes.Single(g => g.Name == "Theatre"), EventName = "Creepy", Description = "...Crawlers", StartDate = Convert.ToDateTime("11/30/20 11:22"), EndDate = Convert.ToDateTime("11/30/20 13:34"), VenueName = "ThingMaker Theatre", VenueCity = "Hollywood", VenueState = "CA", OrganizerName = "Henson", OrganizerEmail = "jhenson@muppetpastor.com" },
                new Event { EventID = 16, MaxTickets = 364, AvailableTickets = 143, Type = eventTypes.Single(g => g.Name == "Convention"), EventName = "Comicon", Description = "If you can't figure it out you shouldn't go", StartDate = Convert.ToDateTime("11/30/19 08:37"), EndDate = Convert.ToDateTime("11/30/19 11:24"), VenueName = "San Diego Convention Center", VenueCity = "San Diego", VenueState = "CA", OrganizerName = "Comic-Con International", OrganizerEmail = "CCInfo@CCI.com" },
                new Event { EventID = 17, MaxTickets = 3828, AvailableTickets = 1979, Type = eventTypes.Single(g => g.Name == "Convention"), EventName = "Creepicon", Description = "A macabre masquerade", StartDate = Convert.ToDateTime("12/06/20 07:36"), EndDate = Convert.ToDateTime("12/07/20 03:26"), VenueName = "Hell's Gate", VenueCity = "Hell", VenueState = "MI", OrganizerName = "Asmodeus", OrganizerEmail = "DemonOfLust@PrincesOfHell.com" },
                new Event { EventID = 18, MaxTickets = 2079, AvailableTickets = 802, Type = eventTypes.Single(g => g.Name == "Festival"), EventName = "Duct Tape Festival", Description = "If you can't duct it...", StartDate = Convert.ToDateTime("11/05/20 00:23"), EndDate = Convert.ToDateTime("11/05/20 17:30"), VenueName = "Veteran's Memorial Park", VenueCity = "Avon", VenueState = "OH", OrganizerName = "Lucy Idol", OrganizerEmail = "iLikeTape@duct.com" },
                new Event { EventID = 19, MaxTickets = 8031, AvailableTickets = 5350, Type = eventTypes.Single(g => g.Name == "Dining"), EventName = "Dropped Dead", Description = "Whatever the local hunter's bring in", StartDate = Convert.ToDateTime("12/19/19 04:24"), EndDate = Convert.ToDateTime("12/19/19 19:31"), VenueName = "Hunter Hall", VenueCity = "Stone Mountain", VenueState = "GA", OrganizerName = "Buck", OrganizerEmail = "12point@huntsman.com" },
                new Event { EventID = 20, MaxTickets = 1115, AvailableTickets = 906, Type = eventTypes.Single(g => g.Name == "Convention"), EventName = "DC Con", Description = "Battery Powered Villians against Marvel", StartDate = Convert.ToDateTime("12/15/19 13:29"), EndDate = Convert.ToDateTime("12/15/19 20:56"), VenueName = "Energizer Areans", VenueCity = "St. Louis", VenueState = "MO", OrganizerName = "Bunny", OrganizerEmail = "PinkBunny@batteries.com" },
                new Event { EventID = 21, MaxTickets = 888, AvailableTickets = 858, Type = eventTypes.Single(g => g.Name == "Dining"), EventName = "Dash and Dine", Description = "Just because it's in the name doesn't mean you should do it", StartDate = Convert.ToDateTime("11/25/20 11:14"), EndDate = Convert.ToDateTime("11/26/20 07:05"), VenueName = "Dash and Dine", VenueCity = "Seattle", VenueState = "WA", OrganizerName = "Joey Chestnut", OrganizerEmail = "Roasted@OpenFire.com" },
                new Event { EventID = 22, MaxTickets = 9993, AvailableTickets = 136, Type = eventTypes.Single(g => g.Name == "Shenanigans"), EventName = "Egging", Description = "No, we aren't dying Easter eggs", StartDate = Convert.ToDateTime("12/22/19 20:28"), EndDate = Convert.ToDateTime("12/23/19 05:20"), VenueName = "The 'Hood", VenueCity = "Pensicola", VenueState = "FL", OrganizerName = "Dave", OrganizerEmail = "iamrotten@foods.com" },
                new Event { EventID = 23, MaxTickets = 1853, AvailableTickets = 769, Type = eventTypes.Single(g => g.Name == "Dining"), EventName = "Egyptian Elegance", Description = "Like sand baked crocodile.", StartDate = Convert.ToDateTime("11/04/20 03:10"), EndDate = Convert.ToDateTime("11/04/20 03:43"), VenueName = "E-Gypt'd", VenueCity = "Phoenix", VenueState = "AZ", OrganizerName = "Ramses", OrganizerEmail = "notGordon@pharoahs.com" },
                new Event { EventID = 24, MaxTickets = 7580, AvailableTickets = 5418, Type = eventTypes.Single(g => g.Name == "Movie"), EventName = "Egypt: The Pyramid Story", Description = "Were they really built by Ancient Aliens?", StartDate = Convert.ToDateTime("12/17/19 15:37"), EndDate = Convert.ToDateTime("12/17/19 12:02"), VenueName = "Sarcophogus Cinema", VenueCity = "Alexandria", VenueState = "NM", OrganizerName = "Horus", OrganizerEmail = "BrotherOfRa@pharohs.com" },
                new Event { EventID = 25, MaxTickets = 9379, AvailableTickets = 5902, Type = eventTypes.Single(g => g.Name == "Dining"), EventName = "Falaffal Factory", Description = "No Shawarma here", StartDate = Convert.ToDateTime("12/13/20 01:35"), EndDate = Convert.ToDateTime("12/13/20 12:52"), VenueName = "Falaffal Factory", VenueCity = "Jordan", VenueState = "GA", OrganizerName = "Hu-Dan", OrganizerEmail = "FalaffalKing@noshawarma.com" },
                new Event { EventID = 26, MaxTickets = 9503, AvailableTickets = 8671, Type = eventTypes.Single(g => g.Name == "Convention"), EventName = "Funk Factory", Description = "Who's got the funk, yeah we got the funk.", StartDate = Convert.ToDateTime("11/11/20 11:01"), EndDate = Convert.ToDateTime("11/12/20 01:11"), VenueName = "Funk Factory", VenueCity = "Philadelphia", VenueState = "PA", OrganizerName = "George", OrganizerEmail = "Phunkadelic@pfunk.com" },
                new Event { EventID = 27, MaxTickets = 3344, AvailableTickets = 1884, Type = eventTypes.Single(g => g.Name == "Theatre"), EventName = "Freshmen: A Highschool Drama", Description = "Everything is Drama when you're 13", StartDate = Convert.ToDateTime("10/28/20 08:11"), EndDate = Convert.ToDateTime("10/28/20 20:02"), VenueName = "Cinema 13", VenueCity = "Miami", VenueState = "FL", OrganizerName = "Suzy Q", OrganizerEmail = "teenageangst@mflhs.edu" },
                new Event { EventID = 28, MaxTickets = 7704, AvailableTickets = 4773, Type = eventTypes.Single(g => g.Name == "Convention"), EventName = "Fraud", Description = "A low priced fake of whatever your heart desires", StartDate = Convert.ToDateTime("12/15/19 05:12"), EndDate = Convert.ToDateTime("12/15/19 08:41"), VenueName = "Water's Gate", VenueCity = "Washington D.C.", VenueState = "DC", OrganizerName = "Tricky Dick", OrganizerEmail = "NotACrook@FormerPres.us" },
                new Event { EventID = 29, MaxTickets = 9525, AvailableTickets = 1005, Type = eventTypes.Single(g => g.Name == "Shenanigans"), EventName = "Gaslighting", Description = "Let's blow some things up", StartDate = Convert.ToDateTime("11/04/19 22:36"), EndDate = Convert.ToDateTime("11/05/19 02:09"), VenueName = "Backyard", VenueCity = "Lodi", VenueState = "OH", OrganizerName = "Billy Ray", OrganizerEmail = "PyroBoy@aol.com" },
                new Event { EventID = 30, MaxTickets = 1245, AvailableTickets = 115, Type = eventTypes.Single(g => g.Name == "Convention"), EventName = "Gamma-con", Description = "Smash!", StartDate = Convert.ToDateTime("12/19/19 00:23"), EndDate = Convert.ToDateTime("12/19/19 21:03"), VenueName = "Gamma Phi Omega House", VenueCity = "Salt Lack City", VenueState = "UT", OrganizerName = "Bruce", OrganizerEmail = "BigGreen@AgentsOfSmash.com" },
                new Event { EventID = 31, MaxTickets = 9855, AvailableTickets = 833, Type = eventTypes.Single(g => g.Name == "Theatre"), EventName = "Green Days: Climate Change", Description = "It can't be denied, not even by flat earthers", StartDate = Convert.ToDateTime("12/27/20 04:20"), EndDate = Convert.ToDateTime("12/27/20 14:59"), VenueName = "Hanging Gardens", VenueCity = "Portland", VenueState = "OR", OrganizerName = "Mr. Gore", OrganizerEmail = "InventedTheInternet@weather.org" },
                new Event { EventID = 32, MaxTickets = 2464, AvailableTickets = 967, Type = eventTypes.Single(g => g.Name == "Theatre"), EventName = "Gone Away: Soliciting Suicide", Description = "Kill yourself...you'll be happy if you do it", StartDate = Convert.ToDateTime("12/24/19 11:45"), EndDate = Convert.ToDateTime("12/24/19 22:29"), VenueName = "Lonely Hall Amphitheatre", VenueCity = "Seattle", VenueState = "WA", OrganizerName = "Bo Yo", OrganizerEmail = "GreatestRapperEver@whetheryourcleverornot.com" },
                new Event { EventID = 33, MaxTickets = 8096, AvailableTickets = 903, Type = eventTypes.Single(g => g.Name == "Convention"), EventName = "Greek Gods", Description = "THIS IS SPARTA!", StartDate = Convert.ToDateTime("12/20/19 16:02"), EndDate = Convert.ToDateTime("12/21/19 15:47"), VenueName = "The Colosseum", VenueCity = "Athens", VenueState = "OH", OrganizerName = "Helena", OrganizerEmail = "DaughterOfZues@Goddess.gr" },
                new Event { EventID = 34, MaxTickets = 5395, AvailableTickets = 3325, Type = eventTypes.Single(g => g.Name == "Movie"), EventName = "Grimoirre", Description = "Necronomicon: The Prequel", StartDate = Convert.ToDateTime("12/20/19 04:08"), EndDate = Convert.ToDateTime("12/20/19 23:32"), VenueName = "Cthulhu Cinema", VenueCity = "Hell", VenueState = "MI", OrganizerName = "G.O. Knudq'es", OrganizerEmail = "horrorsofthedeep@thingsofnightmares.com" },
                new Event { EventID = 35, MaxTickets = 8254, AvailableTickets = 5750, Type = eventTypes.Single(g => g.Name == "Festival"), EventName = "Harvest Moon", Description = "Corn, pumpkins, turducken.", StartDate = Convert.ToDateTime("11/06/20 09:27"), EndDate = Convert.ToDateTime("11/06/20 21:00"), VenueName = "The Fields of Fertility", VenueCity = "Oklahoma City", VenueState = "OK", OrganizerName = "Usagi Tsukino", OrganizerEmail = "ReallySailor@Kodansha.com" },
                new Event { EventID = 36, MaxTickets = 7672, AvailableTickets = 2171, Type = eventTypes.Single(g => g.Name == "Theatre"), EventName = "Iced Over", Description = "When hearts grow cold", StartDate = Convert.ToDateTime("11/30/20 08:08"), EndDate = Convert.ToDateTime("11/30/20 22:05"), VenueName = "Frozen Funland", VenueCity = "Hell", VenueState = "MI", OrganizerName = "Elsa", OrganizerEmail = "IceQueen@DizKnee.com" },
                new Event { EventID = 37, MaxTickets = 6062, AvailableTickets = 5275, Type = eventTypes.Single(g => g.Name == "Theatre"), EventName = "Just Playing", Description = "Tart Transvestites Traveling to Transylvania", StartDate = Convert.ToDateTime("11/01/20 21:09"), EndDate = Convert.ToDateTime("11/02/20 17:45"), VenueName = "RHPS Amphitheatre", VenueCity = "New York", VenueState = "NY", OrganizerName = "Riph Raph", OrganizerEmail = "TheRealMagenta@RHPS.tr" },
                new Event { EventID = 38, MaxTickets = 9197, AvailableTickets = 5357, Type = eventTypes.Single(g => g.Name == "Shenanigans"), EventName = "Jump Yard", Description = "We're going to be like Tigger and bounce", StartDate = Convert.ToDateTime("11/02/20 23:30"), EndDate = Convert.ToDateTime("11/03/20 06:39"), VenueName = "Jump Yard", VenueCity = "Akron", VenueState = "OH", OrganizerName = "Whinney", OrganizerEmail = "ThePoohAndPigletToo@ChrisRobins.com" },
                new Event { EventID = 39, MaxTickets = 3942, AvailableTickets = 1265, Type = eventTypes.Single(g => g.Name == "Shenanigans"), EventName = "Killing Time", Description = "Smashing clocks", StartDate = Convert.ToDateTime("11/17/20 01:50"), EndDate = Convert.ToDateTime("11/17/20 09:41"), VenueName = "Mad Hatter's", VenueCity = "JabberWalke", VenueState = "DW", OrganizerName = "White Rabbit", OrganizerEmail = "DownTheHole@wonderland.net" },
                new Event { EventID = 40, MaxTickets = 7118, AvailableTickets = 4074, Type = eventTypes.Single(g => g.Name == "Movie"), EventName = "Last Tuesday", Description = "Kind of like First Friday", StartDate = Convert.ToDateTime("10/30/20 18:30"), EndDate = Convert.ToDateTime("10/30/20 21:08"), VenueName = "The Calendar", VenueCity = "Boise", VenueState = "ID", OrganizerName = "Mr. Potat", OrganizerEmail = "PushInParts@hasbro.com" },
                new Event { EventID = 41, MaxTickets = 5139, AvailableTickets = 1738, Type = eventTypes.Single(g => g.Name == "Meeting"), EventName = "Halloween", Description = "I am the on hiding under your bed", StartDate = Convert.ToDateTime("10/31/20 01:00"), EndDate = Convert.ToDateTime("10/31/20 23:59"), VenueName = "Pumpkin Patch", VenueCity = "Halloweentown", VenueState = "NV", OrganizerName = "Jack", OrganizerEmail = "ThePumpkinKing@halloween.ha" },
                new Event { EventID = 42, MaxTickets = 8365, AvailableTickets = 3440, Type = eventTypes.Single(g => g.Name == "Convention"), EventName = "New Age", Description = "Crystals, music and yoga, oh my.", StartDate = Convert.ToDateTime("12/20/19 09:48"), EndDate = Convert.ToDateTime("12/20/19 20:45"), VenueName = "Dream Catcher Park", VenueCity = "Hollywood", VenueState = "CA", OrganizerName = "ManBun", OrganizerEmail = "YogaHippyGuru@crystalpower.net" },
                new Event { EventID = 43, MaxTickets = 9579, AvailableTickets = 7116, Type = eventTypes.Single(g => g.Name == "Dining"), EventName = "Olfactory Overload", Description = "Can you smell what the rock is cooking?", StartDate = Convert.ToDateTime("12/17/20 06:28"), EndDate = Convert.ToDateTime("12/17/20 15:24"), VenueName = "Rock Lobster", VenueCity = "Bangor", VenueState = "MN", OrganizerName = "Dee Jonson", OrganizerEmail = "52Rocks@bCooking.net" },
                new Event { EventID = 44, MaxTickets = 498, AvailableTickets = 79, Type = eventTypes.Single(g => g.Name == "Shenanigans"), EventName = "Pink Pony Party", Description = "Someone left their computer unlocked", StartDate = Convert.ToDateTime("12/15/20 07:38"), EndDate = Convert.ToDateTime("12/15/20 13:19"), VenueName = "Workplace", VenueCity = "Cleveland", VenueState = "OH", OrganizerName = "TheGuys", OrganizerEmail = "TheGuys@work.com" },
                new Event { EventID = 45, MaxTickets = 8300, AvailableTickets = 7907, Type = eventTypes.Single(g => g.Name == "Theatre"), EventName = "Queens", Description = "Not of the StoneAge", StartDate = Convert.ToDateTime("12/08/20 16:35"), EndDate = Convert.ToDateTime("12/09/20 16:01"), VenueName = "The Cave", VenueCity = "El Dorado", VenueState = "NM", OrganizerName = "Elvis", OrganizerEmail = "TheKing@NoQueens.com" },
                new Event { EventID = 46, MaxTickets = 4405, AvailableTickets = 1683, Type = eventTypes.Single(g => g.Name == "Concert"), EventName = "Rancid Eggs", Description = "Opening for Moldy Ham, featuring Footie Pajamas", StartDate = Convert.ToDateTime("12/14/19 22:09"), EndDate = Convert.ToDateTime("12/15/19 11:18"), VenueName = "The Cat's Hat", VenueCity = "WhoVille", VenueState = "AK", OrganizerName = "Theodor Geisel", OrganizerEmail = "HortonHears@TheGrich.ru" },
                new Event { EventID = 47, MaxTickets = 4405, AvailableTickets = 1683, Type = eventTypes.Single(g => g.Name == "Sporting Event"), EventName = "Beast Bowl", Description = "Lions, and Tigers, and Bears, oh my", StartDate = Convert.ToDateTime("12/17/20 22:09"), EndDate = Convert.ToDateTime("12/17/20 11:18"), VenueName = "Predator Arena", VenueCity = "Emerald City", VenueState = "KS", OrganizerName = "Dorothy", OrganizerEmail = "TheGreatAndPowerful@wizard.oz" },
            }.ForEach(a => context.Events.Add(a));
        }
    }
}